version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cs490_GP
    networks:
      - my_custom_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    depends_on:
      - mysql
    networks:
      - my_custom_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_custom_network

  selenium:
    build:
      context: .
      dockerfile: Dockerfile.selenium
    depends_on:
      - frontend
    networks:
      - my_custom_network
    environment:
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:5000

networks:
  my_custom_network:
    driver: bridge
