FROM selenium/standalone-chrome

USER root

RUN apt-get update && apt-get install -y python3-venv python3-pip
RUN python3 -m venv /home/seluser/venv
RUN /home/seluser/venv/bin/pip install --no-cache-dir pytest selenium webdriver-manager

ENV PATH="/home/seluser/venv/bin:$PATH"

RUN which chromedriver

USER seluser

ENTRYPOINT ["sh", "-c", "sleep 10 && pytest --disable-warnings /tests > /home/seluser/test_logs.txt"]
