name: Run Python tests

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  MYSQL_ROOT_PASSWORD: "root_password"
  MYSQL_DATABASE: "my_test_db"
  DB_DUMP: "dump.sql"

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -U pytest
          pip install -e .
          pip install webdriver-manager
          sudo apt-get update -y
          sudo apt-get install -y chromium-browser chromium-chromedriver wget libxss1 libappindicator3-1 libindicator7

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
          docker-compose --version

      - name: Set up Docker and start containers
        run: |
          docker-compose up -d
          sleep 60  # Adjust this based on actual startup times

      - name: List files to verify test directory structure
        run: ls -R

      - name: Run Selenium Tests (accepting patients)
        env:
          CHROME_BIN: /usr/bin/chromium-browser
        run: |
          export PATH=$PATH:/usr/local/bin
          export CHROME_OPTIONS="--headless --no-sandbox --disable-dev-shm-usage --remote-debugging-port=9222"
          pytest ./tests/test_acceptingpatients.py --disable-warnings

      - name: Clean up Docker containers
        run: docker-compose down
