name: Run Backend and Frontend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend-frontend:
    name: Start and Test Backend & Frontend
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: cs490_GP
        ports:
          - 3306:3306

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python for the backend
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install backend dependencies and create virtual environment
      - name: Install backend dependencies and create virtual environment
        run: |
          cd backend
          python -m venv venv  # Create virtual environment
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest selenium webdriver-manager
          cd ..

      # Step 4: Set up Node.js for the frontend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # Step 5: Start Backend and Frontend
      - name: Start Backend and Frontend
        run: |
          cd backend
          source venv/bin/activate
          flask run --host=0.0.0.0 --port=5000 &
          cd ../frontend
          npm start &
          sleep 30  # Wait for services to start

      # Step 6: Run all tests (including backend, frontend, and selenium tests)
      - name: Run all tests
        run: |
          cd backend
          source venv/bin/activate
          pytest ../tests/ --disable-warnings  # Run all tests in the tests directory

      # Step 7: Run specific Selenium test file - test_acceptingpatients.py
      - name: Run test_acceptingpatients.py
        run: |
          cd backend
          source venv/bin/activate
          pytest ../tests/test_acceptingpatients.py --disable-warnings  # Run specific test file (Selenium test)
